# build the gateway binary
FROM golang:1.10.0 as builder
WORKDIR /go/src/{{ .Root }}/{{ .Name }}
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o bin/gateway ./cmd/gateway

# build the gateway binary
FROM alpine:latest as runner
WORKDIR /bin
COPY --from=0 /go/src/{{ .Root }}/{{ .Name }}/bin/gateway .
ENTRYPOINT ["gateway"]