[[constraint]]
  branch = "master"
  name = "github.com/infobloxopen/themis"
  
[[constraint]]
  branch = "master"
  name = "github.com/dgrijalva/jwt-go"

[[constraint]]
  branch = "master"
  name = "github.com/golang/protobuf"

[[constraint]]
  branch = "master"
  name = "github.com/grpc-ecosystem/go-grpc-middleware"

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "1.3.1"

[[constraint]]
  name = "github.com/lyft/protoc-gen-validate"
  version = "0.0.5"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "google.golang.org/genproto"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.11.0"

[prune]
  go-tests = true
  unused-packages = true
