# build the server binary
FROM golang:1.10.0 as builder
WORKDIR /go/src/{{ .Root }}/{{ .Name }}
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o bin/server ./cmd/server

# copy the server binary from builder stage; run the server binary
FROM alpine:latest as runner
WORKDIR /bin
COPY --from=0 /go/src/{{ .Root }}/{{ .Name }}/bin/server .
ENTRYPOINT ["server"]