// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/infobloxopen/atlas-app-toolkit/query/collection_operators.proto

package query

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Order is a sort order.
type SortCriteria_Order int32

const (
	// ascending sort order
	SortCriteria_ASC SortCriteria_Order = 0
	// descending sort order
	SortCriteria_DESC SortCriteria_Order = 1
)

var SortCriteria_Order_name = map[int32]string{
	0: "ASC",
	1: "DESC",
}

var SortCriteria_Order_value = map[string]int32{
	"ASC":  0,
	"DESC": 1,
}

func (x SortCriteria_Order) String() string {
	return proto.EnumName(SortCriteria_Order_name, int32(x))
}

func (SortCriteria_Order) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7b72dfd3c08d3120, []int{0, 0}
}

type LogicalOperator_Type int32

const (
	LogicalOperator_AND LogicalOperator_Type = 0
	LogicalOperator_OR  LogicalOperator_Type = 1
)

var LogicalOperator_Type_name = map[int32]string{
	0: "AND",
	1: "OR",
}

var LogicalOperator_Type_value = map[string]int32{
	"AND": 0,
	"OR":  1,
}

func (x LogicalOperator_Type) String() string {
	return proto.EnumName(LogicalOperator_Type_name, int32(x))
}

func (LogicalOperator_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7b72dfd3c08d3120, []int{5, 0}
}

type StringCondition_Type int32

const (
	StringCondition_EQ    StringCondition_Type = 0
	StringCondition_MATCH StringCondition_Type = 1
	StringCondition_GT    StringCondition_Type = 2
	StringCondition_GE    StringCondition_Type = 3
	StringCondition_LT    StringCondition_Type = 4
	StringCondition_LE    StringCondition_Type = 5
	StringCondition_IEQ   StringCondition_Type = 6
)

var StringCondition_Type_name = map[int32]string{
	0: "EQ",
	1: "MATCH",
	2: "GT",
	3: "GE",
	4: "LT",
	5: "LE",
	6: "IEQ",
}

var StringCondition_Type_value = map[string]int32{
	"EQ":    0,
	"MATCH": 1,
	"GT":    2,
	"GE":    3,
	"LT":    4,
	"LE":    5,
	"IEQ":   6,
}

func (x StringCondition_Type) String() string {
	return proto.EnumName(StringCondition_Type_name, int32(x))
}

func (StringCondition_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7b72dfd3c08d3120, []int{6, 0}
}

type NumberCondition_Type int32

const (
	NumberCondition_EQ NumberCondition_Type = 0
	NumberCondition_GT NumberCondition_Type = 1
	NumberCondition_GE NumberCondition_Type = 2
	NumberCondition_LT NumberCondition_Type = 3
	NumberCondition_LE NumberCondition_Type = 4
)

var NumberCondition_Type_name = map[int32]string{
	0: "EQ",
	1: "GT",
	2: "GE",
	3: "LT",
	4: "LE",
}

var NumberCondition_Type_value = map[string]int32{
	"EQ": 0,
	"GT": 1,
	"GE": 2,
	"LT": 3,
	"LE": 4,
}

func (x NumberCondition_Type) String() string {
	return proto.EnumName(NumberCondition_Type_name, int32(x))
}

func (NumberCondition_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7b72dfd3c08d3120, []int{7, 0}
}

type StringArrayCondition_Type int32

const (
	StringArrayCondition_IN StringArrayCondition_Type = 0
)

var StringArrayCondition_Type_name = map[int32]string{
	0: "IN",
}

var StringArrayCondition_Type_value = map[string]int32{
	"IN": 0,
}

func (x StringArrayCondition_Type) String() string {
	return proto.EnumName(StringArrayCondition_Type_name, int32(x))
}

func (StringArrayCondition_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7b72dfd3c08d3120, []int{9, 0}
}

type NumberArrayCondition_Type int32

const (
	NumberArrayCondition_IN NumberArrayCondition_Type = 0
)

var NumberArrayCondition_Type_name = map[int32]string{
	0: "IN",
}

var NumberArrayCondition_Type_value = map[string]int32{
	"IN": 0,
}

func (x NumberArrayCondition_Type) String() string {
	return proto.EnumName(NumberArrayCondition_Type_name, int32(x))
}

func (NumberArrayCondition_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7b72dfd3c08d3120, []int{10, 0}
}

// SortCriteria represents sort criteria
type SortCriteria struct {
	// Tag is a JSON tag.
	Tag                  string             `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Order                SortCriteria_Order `protobuf:"varint,2,opt,name=order,proto3,enum=infoblox.api.SortCriteria_Order" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SortCriteria) Reset()         { *m = SortCriteria{} }
func (m *SortCriteria) String() string { return proto.CompactTextString(m) }
func (*SortCriteria) ProtoMessage()    {}
func (*SortCriteria) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b72dfd3c08d3120, []int{0}
}

func (m *SortCriteria) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SortCriteria.Unmarshal(m, b)
}
func (m *SortCriteria) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SortCriteria.Marshal(b, m, deterministic)
}
func (m *SortCriteria) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SortCriteria.Merge(m, src)
}
func (m *SortCriteria) XXX_Size() int {
	return xxx_messageInfo_SortCriteria.Size(m)
}
func (m *SortCriteria) XXX_DiscardUnknown() {
	xxx_messageInfo_SortCriteria.DiscardUnknown(m)
}

var xxx_messageInfo_SortCriteria proto.InternalMessageInfo

func (m *SortCriteria) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *SortCriteria) GetOrder() SortCriteria_Order {
	if m != nil {
		return m.Order
	}
	return SortCriteria_ASC
}

// Sorting represents list of sort criterias.
type Sorting struct {
	Criterias            []*SortCriteria `protobuf:"bytes,1,rep,name=criterias,proto3" json:"criterias,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Sorting) Reset()         { *m = Sorting{} }
func (m *Sorting) String() string { return proto.CompactTextString(m) }
func (*Sorting) ProtoMessage()    {}
func (*Sorting) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b72dfd3c08d3120, []int{1}
}

func (m *Sorting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sorting.Unmarshal(m, b)
}
func (m *Sorting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sorting.Marshal(b, m, deterministic)
}
func (m *Sorting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sorting.Merge(m, src)
}
func (m *Sorting) XXX_Size() int {
	return xxx_messageInfo_Sorting.Size(m)
}
func (m *Sorting) XXX_DiscardUnknown() {
	xxx_messageInfo_Sorting.DiscardUnknown(m)
}

var xxx_messageInfo_Sorting proto.InternalMessageInfo

func (m *Sorting) GetCriterias() []*SortCriteria {
	if m != nil {
		return m.Criterias
	}
	return nil
}

// FieldSelection represents a group of fields for some object.
// Main use case for if is to store information about object fields that
// need to be ratained prior to sending object as a response
type FieldSelection struct {
	Fields               map[string]*Field `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *FieldSelection) Reset()         { *m = FieldSelection{} }
func (m *FieldSelection) String() string { return proto.CompactTextString(m) }
func (*FieldSelection) ProtoMessage()    {}
func (*FieldSelection) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b72dfd3c08d3120, []int{2}
}

func (m *FieldSelection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldSelection.Unmarshal(m, b)
}
func (m *FieldSelection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldSelection.Marshal(b, m, deterministic)
}
func (m *FieldSelection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldSelection.Merge(m, src)
}
func (m *FieldSelection) XXX_Size() int {
	return xxx_messageInfo_FieldSelection.Size(m)
}
func (m *FieldSelection) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldSelection.DiscardUnknown(m)
}

var xxx_messageInfo_FieldSelection proto.InternalMessageInfo

func (m *FieldSelection) GetFields() map[string]*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

// Field represents a single field for an object.
// It contains fields name and also may contain a group of sub-fields for cases
// when a fields represents some structure.
type Field struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Subs                 map[string]*Field `protobuf:"bytes,2,rep,name=subs,proto3" json:"subs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Field) Reset()         { *m = Field{} }
func (m *Field) String() string { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()    {}
func (*Field) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b72dfd3c08d3120, []int{3}
}

func (m *Field) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Field.Unmarshal(m, b)
}
func (m *Field) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Field.Marshal(b, m, deterministic)
}
func (m *Field) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Field.Merge(m, src)
}
func (m *Field) XXX_Size() int {
	return xxx_messageInfo_Field.Size(m)
}
func (m *Field) XXX_DiscardUnknown() {
	xxx_messageInfo_Field.DiscardUnknown(m)
}

var xxx_messageInfo_Field proto.InternalMessageInfo

func (m *Field) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Field) GetSubs() map[string]*Field {
	if m != nil {
		return m.Subs
	}
	return nil
}

// Filtering represents filtering expression.
// root could be either LogicalOperator or one of the supported conditions.
type Filtering struct {
	// Types that are valid to be assigned to Root:
	//	*Filtering_Operator
	//	*Filtering_StringCondition
	//	*Filtering_NumberCondition
	//	*Filtering_NullCondition
	//	*Filtering_StringArrayCondition
	//	*Filtering_NumberArrayCondition
	Root                 isFiltering_Root `protobuf_oneof:"root"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Filtering) Reset()         { *m = Filtering{} }
func (m *Filtering) String() string { return proto.CompactTextString(m) }
func (*Filtering) ProtoMessage()    {}
func (*Filtering) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b72dfd3c08d3120, []int{4}
}

func (m *Filtering) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filtering.Unmarshal(m, b)
}
func (m *Filtering) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filtering.Marshal(b, m, deterministic)
}
func (m *Filtering) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filtering.Merge(m, src)
}
func (m *Filtering) XXX_Size() int {
	return xxx_messageInfo_Filtering.Size(m)
}
func (m *Filtering) XXX_DiscardUnknown() {
	xxx_messageInfo_Filtering.DiscardUnknown(m)
}

var xxx_messageInfo_Filtering proto.InternalMessageInfo

type isFiltering_Root interface {
	isFiltering_Root()
}

type Filtering_Operator struct {
	Operator *LogicalOperator `protobuf:"bytes,1,opt,name=operator,proto3,oneof"`
}

type Filtering_StringCondition struct {
	StringCondition *StringCondition `protobuf:"bytes,2,opt,name=string_condition,json=stringCondition,proto3,oneof"`
}

type Filtering_NumberCondition struct {
	NumberCondition *NumberCondition `protobuf:"bytes,3,opt,name=number_condition,json=numberCondition,proto3,oneof"`
}

type Filtering_NullCondition struct {
	NullCondition *NullCondition `protobuf:"bytes,4,opt,name=null_condition,json=nullCondition,proto3,oneof"`
}

type Filtering_StringArrayCondition struct {
	StringArrayCondition *StringArrayCondition `protobuf:"bytes,5,opt,name=string_array_condition,json=stringArrayCondition,proto3,oneof"`
}

type Filtering_NumberArrayCondition struct {
	NumberArrayCondition *NumberArrayCondition `protobuf:"bytes,6,opt,name=number_array_condition,json=numberArrayCondition,proto3,oneof"`
}

func (*Filtering_Operator) isFiltering_Root() {}

func (*Filtering_StringCondition) isFiltering_Root() {}

func (*Filtering_NumberCondition) isFiltering_Root() {}

func (*Filtering_NullCondition) isFiltering_Root() {}

func (*Filtering_StringArrayCondition) isFiltering_Root() {}

func (*Filtering_NumberArrayCondition) isFiltering_Root() {}

func (m *Filtering) GetRoot() isFiltering_Root {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *Filtering) GetOperator() *LogicalOperator {
	if x, ok := m.GetRoot().(*Filtering_Operator); ok {
		return x.Operator
	}
	return nil
}

func (m *Filtering) GetStringCondition() *StringCondition {
	if x, ok := m.GetRoot().(*Filtering_StringCondition); ok {
		return x.StringCondition
	}
	return nil
}

func (m *Filtering) GetNumberCondition() *NumberCondition {
	if x, ok := m.GetRoot().(*Filtering_NumberCondition); ok {
		return x.NumberCondition
	}
	return nil
}

func (m *Filtering) GetNullCondition() *NullCondition {
	if x, ok := m.GetRoot().(*Filtering_NullCondition); ok {
		return x.NullCondition
	}
	return nil
}

func (m *Filtering) GetStringArrayCondition() *StringArrayCondition {
	if x, ok := m.GetRoot().(*Filtering_StringArrayCondition); ok {
		return x.StringArrayCondition
	}
	return nil
}

func (m *Filtering) GetNumberArrayCondition() *NumberArrayCondition {
	if x, ok := m.GetRoot().(*Filtering_NumberArrayCondition); ok {
		return x.NumberArrayCondition
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Filtering) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Filtering_Operator)(nil),
		(*Filtering_StringCondition)(nil),
		(*Filtering_NumberCondition)(nil),
		(*Filtering_NullCondition)(nil),
		(*Filtering_StringArrayCondition)(nil),
		(*Filtering_NumberArrayCondition)(nil),
	}
}

// LogicalOperator represents binary logical operator, either AND or OR depending on type.
// left and right are respectively left and right operands of the operator, could be
// either LogicalOperator or one of the supported conditions.
// is_negative is set to true if the operator is negated.
type LogicalOperator struct {
	// Types that are valid to be assigned to Left:
	//	*LogicalOperator_LeftOperator
	//	*LogicalOperator_LeftStringCondition
	//	*LogicalOperator_LeftNumberCondition
	//	*LogicalOperator_LeftNullCondition
	//	*LogicalOperator_LeftStringArrayCondition
	//	*LogicalOperator_LeftNumberArrayCondition
	Left isLogicalOperator_Left `protobuf_oneof:"left"`
	// Types that are valid to be assigned to Right:
	//	*LogicalOperator_RightOperator
	//	*LogicalOperator_RightStringCondition
	//	*LogicalOperator_RightNumberCondition
	//	*LogicalOperator_RightNullCondition
	//	*LogicalOperator_RightStringArrayCondition
	//	*LogicalOperator_RightNumberArrayCondition
	Right                isLogicalOperator_Right `protobuf_oneof:"right"`
	Type                 LogicalOperator_Type    `protobuf:"varint,9,opt,name=type,proto3,enum=infoblox.api.LogicalOperator_Type" json:"type,omitempty"`
	IsNegative           bool                    `protobuf:"varint,10,opt,name=is_negative,json=isNegative,proto3" json:"is_negative,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *LogicalOperator) Reset()         { *m = LogicalOperator{} }
func (m *LogicalOperator) String() string { return proto.CompactTextString(m) }
func (*LogicalOperator) ProtoMessage()    {}
func (*LogicalOperator) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b72dfd3c08d3120, []int{5}
}

func (m *LogicalOperator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogicalOperator.Unmarshal(m, b)
}
func (m *LogicalOperator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogicalOperator.Marshal(b, m, deterministic)
}
func (m *LogicalOperator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogicalOperator.Merge(m, src)
}
func (m *LogicalOperator) XXX_Size() int {
	return xxx_messageInfo_LogicalOperator.Size(m)
}
func (m *LogicalOperator) XXX_DiscardUnknown() {
	xxx_messageInfo_LogicalOperator.DiscardUnknown(m)
}

var xxx_messageInfo_LogicalOperator proto.InternalMessageInfo

type isLogicalOperator_Left interface {
	isLogicalOperator_Left()
}

type LogicalOperator_LeftOperator struct {
	LeftOperator *LogicalOperator `protobuf:"bytes,1,opt,name=left_operator,json=leftOperator,proto3,oneof"`
}

type LogicalOperator_LeftStringCondition struct {
	LeftStringCondition *StringCondition `protobuf:"bytes,2,opt,name=left_string_condition,json=leftStringCondition,proto3,oneof"`
}

type LogicalOperator_LeftNumberCondition struct {
	LeftNumberCondition *NumberCondition `protobuf:"bytes,3,opt,name=left_number_condition,json=leftNumberCondition,proto3,oneof"`
}

type LogicalOperator_LeftNullCondition struct {
	LeftNullCondition *NullCondition `protobuf:"bytes,4,opt,name=left_null_condition,json=leftNullCondition,proto3,oneof"`
}

type LogicalOperator_LeftStringArrayCondition struct {
	LeftStringArrayCondition *StringArrayCondition `protobuf:"bytes,11,opt,name=left_string_array_condition,json=leftStringArrayCondition,proto3,oneof"`
}

type LogicalOperator_LeftNumberArrayCondition struct {
	LeftNumberArrayCondition *NumberArrayCondition `protobuf:"bytes,12,opt,name=left_number_array_condition,json=leftNumberArrayCondition,proto3,oneof"`
}

func (*LogicalOperator_LeftOperator) isLogicalOperator_Left() {}

func (*LogicalOperator_LeftStringCondition) isLogicalOperator_Left() {}

func (*LogicalOperator_LeftNumberCondition) isLogicalOperator_Left() {}

func (*LogicalOperator_LeftNullCondition) isLogicalOperator_Left() {}

func (*LogicalOperator_LeftStringArrayCondition) isLogicalOperator_Left() {}

func (*LogicalOperator_LeftNumberArrayCondition) isLogicalOperator_Left() {}

func (m *LogicalOperator) GetLeft() isLogicalOperator_Left {
	if m != nil {
		return m.Left
	}
	return nil
}

func (m *LogicalOperator) GetLeftOperator() *LogicalOperator {
	if x, ok := m.GetLeft().(*LogicalOperator_LeftOperator); ok {
		return x.LeftOperator
	}
	return nil
}

func (m *LogicalOperator) GetLeftStringCondition() *StringCondition {
	if x, ok := m.GetLeft().(*LogicalOperator_LeftStringCondition); ok {
		return x.LeftStringCondition
	}
	return nil
}

func (m *LogicalOperator) GetLeftNumberCondition() *NumberCondition {
	if x, ok := m.GetLeft().(*LogicalOperator_LeftNumberCondition); ok {
		return x.LeftNumberCondition
	}
	return nil
}

func (m *LogicalOperator) GetLeftNullCondition() *NullCondition {
	if x, ok := m.GetLeft().(*LogicalOperator_LeftNullCondition); ok {
		return x.LeftNullCondition
	}
	return nil
}

func (m *LogicalOperator) GetLeftStringArrayCondition() *StringArrayCondition {
	if x, ok := m.GetLeft().(*LogicalOperator_LeftStringArrayCondition); ok {
		return x.LeftStringArrayCondition
	}
	return nil
}

func (m *LogicalOperator) GetLeftNumberArrayCondition() *NumberArrayCondition {
	if x, ok := m.GetLeft().(*LogicalOperator_LeftNumberArrayCondition); ok {
		return x.LeftNumberArrayCondition
	}
	return nil
}

type isLogicalOperator_Right interface {
	isLogicalOperator_Right()
}

type LogicalOperator_RightOperator struct {
	RightOperator *LogicalOperator `protobuf:"bytes,5,opt,name=right_operator,json=rightOperator,proto3,oneof"`
}

type LogicalOperator_RightStringCondition struct {
	RightStringCondition *StringCondition `protobuf:"bytes,6,opt,name=right_string_condition,json=rightStringCondition,proto3,oneof"`
}

type LogicalOperator_RightNumberCondition struct {
	RightNumberCondition *NumberCondition `protobuf:"bytes,7,opt,name=right_number_condition,json=rightNumberCondition,proto3,oneof"`
}

type LogicalOperator_RightNullCondition struct {
	RightNullCondition *NullCondition `protobuf:"bytes,8,opt,name=right_null_condition,json=rightNullCondition,proto3,oneof"`
}

type LogicalOperator_RightStringArrayCondition struct {
	RightStringArrayCondition *StringArrayCondition `protobuf:"bytes,13,opt,name=right_string_array_condition,json=rightStringArrayCondition,proto3,oneof"`
}

type LogicalOperator_RightNumberArrayCondition struct {
	RightNumberArrayCondition *NumberArrayCondition `protobuf:"bytes,14,opt,name=right_number_array_condition,json=rightNumberArrayCondition,proto3,oneof"`
}

func (*LogicalOperator_RightOperator) isLogicalOperator_Right() {}

func (*LogicalOperator_RightStringCondition) isLogicalOperator_Right() {}

func (*LogicalOperator_RightNumberCondition) isLogicalOperator_Right() {}

func (*LogicalOperator_RightNullCondition) isLogicalOperator_Right() {}

func (*LogicalOperator_RightStringArrayCondition) isLogicalOperator_Right() {}

func (*LogicalOperator_RightNumberArrayCondition) isLogicalOperator_Right() {}

func (m *LogicalOperator) GetRight() isLogicalOperator_Right {
	if m != nil {
		return m.Right
	}
	return nil
}

func (m *LogicalOperator) GetRightOperator() *LogicalOperator {
	if x, ok := m.GetRight().(*LogicalOperator_RightOperator); ok {
		return x.RightOperator
	}
	return nil
}

func (m *LogicalOperator) GetRightStringCondition() *StringCondition {
	if x, ok := m.GetRight().(*LogicalOperator_RightStringCondition); ok {
		return x.RightStringCondition
	}
	return nil
}

func (m *LogicalOperator) GetRightNumberCondition() *NumberCondition {
	if x, ok := m.GetRight().(*LogicalOperator_RightNumberCondition); ok {
		return x.RightNumberCondition
	}
	return nil
}

func (m *LogicalOperator) GetRightNullCondition() *NullCondition {
	if x, ok := m.GetRight().(*LogicalOperator_RightNullCondition); ok {
		return x.RightNullCondition
	}
	return nil
}

func (m *LogicalOperator) GetRightStringArrayCondition() *StringArrayCondition {
	if x, ok := m.GetRight().(*LogicalOperator_RightStringArrayCondition); ok {
		return x.RightStringArrayCondition
	}
	return nil
}

func (m *LogicalOperator) GetRightNumberArrayCondition() *NumberArrayCondition {
	if x, ok := m.GetRight().(*LogicalOperator_RightNumberArrayCondition); ok {
		return x.RightNumberArrayCondition
	}
	return nil
}

func (m *LogicalOperator) GetType() LogicalOperator_Type {
	if m != nil {
		return m.Type
	}
	return LogicalOperator_AND
}

func (m *LogicalOperator) GetIsNegative() bool {
	if m != nil {
		return m.IsNegative
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*LogicalOperator) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*LogicalOperator_LeftOperator)(nil),
		(*LogicalOperator_LeftStringCondition)(nil),
		(*LogicalOperator_LeftNumberCondition)(nil),
		(*LogicalOperator_LeftNullCondition)(nil),
		(*LogicalOperator_LeftStringArrayCondition)(nil),
		(*LogicalOperator_LeftNumberArrayCondition)(nil),
		(*LogicalOperator_RightOperator)(nil),
		(*LogicalOperator_RightStringCondition)(nil),
		(*LogicalOperator_RightNumberCondition)(nil),
		(*LogicalOperator_RightNullCondition)(nil),
		(*LogicalOperator_RightStringArrayCondition)(nil),
		(*LogicalOperator_RightNumberArrayCondition)(nil),
	}
}

// StringCondition represents a condition with a string literal, e.g. field == 'string'.
// field_path is a reference to a value of a resource.
// value is the string literal.
// type is a type of the condition.
// is_negative is set to true if the condition is negated.
type StringCondition struct {
	FieldPath            []string             `protobuf:"bytes,1,rep,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	Value                string               `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Type                 StringCondition_Type `protobuf:"varint,3,opt,name=type,proto3,enum=infoblox.api.StringCondition_Type" json:"type,omitempty"`
	IsNegative           bool                 `protobuf:"varint,4,opt,name=is_negative,json=isNegative,proto3" json:"is_negative,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *StringCondition) Reset()         { *m = StringCondition{} }
func (m *StringCondition) String() string { return proto.CompactTextString(m) }
func (*StringCondition) ProtoMessage()    {}
func (*StringCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b72dfd3c08d3120, []int{6}
}

func (m *StringCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringCondition.Unmarshal(m, b)
}
func (m *StringCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringCondition.Marshal(b, m, deterministic)
}
func (m *StringCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringCondition.Merge(m, src)
}
func (m *StringCondition) XXX_Size() int {
	return xxx_messageInfo_StringCondition.Size(m)
}
func (m *StringCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_StringCondition.DiscardUnknown(m)
}

var xxx_messageInfo_StringCondition proto.InternalMessageInfo

func (m *StringCondition) GetFieldPath() []string {
	if m != nil {
		return m.FieldPath
	}
	return nil
}

func (m *StringCondition) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *StringCondition) GetType() StringCondition_Type {
	if m != nil {
		return m.Type
	}
	return StringCondition_EQ
}

func (m *StringCondition) GetIsNegative() bool {
	if m != nil {
		return m.IsNegative
	}
	return false
}

// NumberCondition represents a condition with a number literal, e.g. field > 3.
// field_path is a reference to a value of a resource.
// value is the number literal.
// type is a type of the condition.
// is_negative is set to true if the condition is negated.
type NumberCondition struct {
	FieldPath            []string             `protobuf:"bytes,1,rep,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	Value                float64              `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Type                 NumberCondition_Type `protobuf:"varint,3,opt,name=type,proto3,enum=infoblox.api.NumberCondition_Type" json:"type,omitempty"`
	IsNegative           bool                 `protobuf:"varint,4,opt,name=is_negative,json=isNegative,proto3" json:"is_negative,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *NumberCondition) Reset()         { *m = NumberCondition{} }
func (m *NumberCondition) String() string { return proto.CompactTextString(m) }
func (*NumberCondition) ProtoMessage()    {}
func (*NumberCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b72dfd3c08d3120, []int{7}
}

func (m *NumberCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NumberCondition.Unmarshal(m, b)
}
func (m *NumberCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NumberCondition.Marshal(b, m, deterministic)
}
func (m *NumberCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NumberCondition.Merge(m, src)
}
func (m *NumberCondition) XXX_Size() int {
	return xxx_messageInfo_NumberCondition.Size(m)
}
func (m *NumberCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_NumberCondition.DiscardUnknown(m)
}

var xxx_messageInfo_NumberCondition proto.InternalMessageInfo

func (m *NumberCondition) GetFieldPath() []string {
	if m != nil {
		return m.FieldPath
	}
	return nil
}

func (m *NumberCondition) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *NumberCondition) GetType() NumberCondition_Type {
	if m != nil {
		return m.Type
	}
	return NumberCondition_EQ
}

func (m *NumberCondition) GetIsNegative() bool {
	if m != nil {
		return m.IsNegative
	}
	return false
}

// NullCondition represents a condition with a null literal, e.g. field == null.
// field_path is a reference to a value of a resource.
// is_negative is set to true if the condition is negated.
type NullCondition struct {
	FieldPath            []string `protobuf:"bytes,1,rep,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	IsNegative           bool     `protobuf:"varint,2,opt,name=is_negative,json=isNegative,proto3" json:"is_negative,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NullCondition) Reset()         { *m = NullCondition{} }
func (m *NullCondition) String() string { return proto.CompactTextString(m) }
func (*NullCondition) ProtoMessage()    {}
func (*NullCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b72dfd3c08d3120, []int{8}
}

func (m *NullCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NullCondition.Unmarshal(m, b)
}
func (m *NullCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NullCondition.Marshal(b, m, deterministic)
}
func (m *NullCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NullCondition.Merge(m, src)
}
func (m *NullCondition) XXX_Size() int {
	return xxx_messageInfo_NullCondition.Size(m)
}
func (m *NullCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_NullCondition.DiscardUnknown(m)
}

var xxx_messageInfo_NullCondition proto.InternalMessageInfo

func (m *NullCondition) GetFieldPath() []string {
	if m != nil {
		return m.FieldPath
	}
	return nil
}

func (m *NullCondition) GetIsNegative() bool {
	if m != nil {
		return m.IsNegative
	}
	return false
}

// StringArrayCondition represents a condition with string arrays, e.g. field in ['hello','world']
// field_path is a reference to a value of a resource.
// is_negative is set to true if the condition is negated
type StringArrayCondition struct {
	FieldPath            []string                  `protobuf:"bytes,1,rep,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	Values               []string                  `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	Type                 StringArrayCondition_Type `protobuf:"varint,3,opt,name=type,proto3,enum=infoblox.api.StringArrayCondition_Type" json:"type,omitempty"`
	IsNegative           bool                      `protobuf:"varint,4,opt,name=is_negative,json=isNegative,proto3" json:"is_negative,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *StringArrayCondition) Reset()         { *m = StringArrayCondition{} }
func (m *StringArrayCondition) String() string { return proto.CompactTextString(m) }
func (*StringArrayCondition) ProtoMessage()    {}
func (*StringArrayCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b72dfd3c08d3120, []int{9}
}

func (m *StringArrayCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringArrayCondition.Unmarshal(m, b)
}
func (m *StringArrayCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringArrayCondition.Marshal(b, m, deterministic)
}
func (m *StringArrayCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringArrayCondition.Merge(m, src)
}
func (m *StringArrayCondition) XXX_Size() int {
	return xxx_messageInfo_StringArrayCondition.Size(m)
}
func (m *StringArrayCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_StringArrayCondition.DiscardUnknown(m)
}

var xxx_messageInfo_StringArrayCondition proto.InternalMessageInfo

func (m *StringArrayCondition) GetFieldPath() []string {
	if m != nil {
		return m.FieldPath
	}
	return nil
}

func (m *StringArrayCondition) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *StringArrayCondition) GetType() StringArrayCondition_Type {
	if m != nil {
		return m.Type
	}
	return StringArrayCondition_IN
}

func (m *StringArrayCondition) GetIsNegative() bool {
	if m != nil {
		return m.IsNegative
	}
	return false
}

// NumberArrayCondition represents a condition with string arrays, e.g. field in [1, 5, 7]
// field_path is a reference to a value of a resource.
// is_negative is set to true if the condition is negated
type NumberArrayCondition struct {
	FieldPath            []string                  `protobuf:"bytes,1,rep,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	Values               []float64                 `protobuf:"fixed64,2,rep,packed,name=values,proto3" json:"values,omitempty"`
	Type                 NumberArrayCondition_Type `protobuf:"varint,3,opt,name=type,proto3,enum=infoblox.api.NumberArrayCondition_Type" json:"type,omitempty"`
	IsNegative           bool                      `protobuf:"varint,4,opt,name=is_negative,json=isNegative,proto3" json:"is_negative,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *NumberArrayCondition) Reset()         { *m = NumberArrayCondition{} }
func (m *NumberArrayCondition) String() string { return proto.CompactTextString(m) }
func (*NumberArrayCondition) ProtoMessage()    {}
func (*NumberArrayCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b72dfd3c08d3120, []int{10}
}

func (m *NumberArrayCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NumberArrayCondition.Unmarshal(m, b)
}
func (m *NumberArrayCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NumberArrayCondition.Marshal(b, m, deterministic)
}
func (m *NumberArrayCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NumberArrayCondition.Merge(m, src)
}
func (m *NumberArrayCondition) XXX_Size() int {
	return xxx_messageInfo_NumberArrayCondition.Size(m)
}
func (m *NumberArrayCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_NumberArrayCondition.DiscardUnknown(m)
}

var xxx_messageInfo_NumberArrayCondition proto.InternalMessageInfo

func (m *NumberArrayCondition) GetFieldPath() []string {
	if m != nil {
		return m.FieldPath
	}
	return nil
}

func (m *NumberArrayCondition) GetValues() []float64 {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *NumberArrayCondition) GetType() NumberArrayCondition_Type {
	if m != nil {
		return m.Type
	}
	return NumberArrayCondition_IN
}

func (m *NumberArrayCondition) GetIsNegative() bool {
	if m != nil {
		return m.IsNegative
	}
	return false
}

// Pagination represents both server-driven and client-driven pagination request.
// Server-driven pagination is a model in which the server returns some
// amount of data along with an token indicating there is more data
// and where subsequent queries can get the next page of data.
// Client-driven pagination is a model in which rows are addressable by
// offset and page size (limit).
type Pagination struct {
	// The service-defined string used to identify a page of resources.
	// A null value indicates the first page.
	PageToken string `protobuf:"bytes,1,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// The integer index of the offset into a collection of resources.
	// If omitted or null the value is assumed to be "0".
	Offset int32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	// The integer number of resources to be returned in the response.
	// The service may impose maximum value.
	// If omitted the service may impose a default value.
	Limit int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	//The bool value enables/disables the record count.
	//The default setting disables the record count.
	IsTotalSize          bool     `protobuf:"varint,4,opt,name=is_total_size,json=isTotalSize,proto3" json:"is_total_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pagination) Reset()         { *m = Pagination{} }
func (m *Pagination) String() string { return proto.CompactTextString(m) }
func (*Pagination) ProtoMessage()    {}
func (*Pagination) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b72dfd3c08d3120, []int{11}
}

func (m *Pagination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pagination.Unmarshal(m, b)
}
func (m *Pagination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pagination.Marshal(b, m, deterministic)
}
func (m *Pagination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pagination.Merge(m, src)
}
func (m *Pagination) XXX_Size() int {
	return xxx_messageInfo_Pagination.Size(m)
}
func (m *Pagination) XXX_DiscardUnknown() {
	xxx_messageInfo_Pagination.DiscardUnknown(m)
}

var xxx_messageInfo_Pagination proto.InternalMessageInfo

func (m *Pagination) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

func (m *Pagination) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Pagination) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Pagination) GetIsTotalSize() bool {
	if m != nil {
		return m.IsTotalSize
	}
	return false
}

// PageInfo represents both server-driven and client-driven pagination response.
// Server-driven pagination is a model in which the server returns some
// amount of data along with an token indicating there is more data
// and where subsequent queries can get the next page of data.
// Client-driven pagination is a model in which rows are addressable by
// offset and page size (limit).
type PageInfo struct {
	// The service response should contain a string to indicate
	// the next page of resources.
	// A null value indicates no more pages.
	PageToken string `protobuf:"bytes,1,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// The service may optionally include the total number of resources being paged.
	Size int32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// The service may optionally include the offset of the next page of resources.
	// A null value indicates no more pages.
	Offset int32 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	//Resultset record count.
	TotalSize            int64    `protobuf:"varint,4,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageInfo) Reset()         { *m = PageInfo{} }
func (m *PageInfo) String() string { return proto.CompactTextString(m) }
func (*PageInfo) ProtoMessage()    {}
func (*PageInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b72dfd3c08d3120, []int{12}
}

func (m *PageInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageInfo.Unmarshal(m, b)
}
func (m *PageInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageInfo.Marshal(b, m, deterministic)
}
func (m *PageInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageInfo.Merge(m, src)
}
func (m *PageInfo) XXX_Size() int {
	return xxx_messageInfo_PageInfo.Size(m)
}
func (m *PageInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PageInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PageInfo proto.InternalMessageInfo

func (m *PageInfo) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

func (m *PageInfo) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *PageInfo) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *PageInfo) GetTotalSize() int64 {
	if m != nil {
		return m.TotalSize
	}
	return 0
}

// Searching represents search by.
type Searching struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Searching) Reset()         { *m = Searching{} }
func (m *Searching) String() string { return proto.CompactTextString(m) }
func (*Searching) ProtoMessage()    {}
func (*Searching) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b72dfd3c08d3120, []int{13}
}

func (m *Searching) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Searching.Unmarshal(m, b)
}
func (m *Searching) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Searching.Marshal(b, m, deterministic)
}
func (m *Searching) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Searching.Merge(m, src)
}
func (m *Searching) XXX_Size() int {
	return xxx_messageInfo_Searching.Size(m)
}
func (m *Searching) XXX_DiscardUnknown() {
	xxx_messageInfo_Searching.DiscardUnknown(m)
}

var xxx_messageInfo_Searching proto.InternalMessageInfo

func (m *Searching) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func init() {
	proto.RegisterEnum("infoblox.api.SortCriteria_Order", SortCriteria_Order_name, SortCriteria_Order_value)
	proto.RegisterEnum("infoblox.api.LogicalOperator_Type", LogicalOperator_Type_name, LogicalOperator_Type_value)
	proto.RegisterEnum("infoblox.api.StringCondition_Type", StringCondition_Type_name, StringCondition_Type_value)
	proto.RegisterEnum("infoblox.api.NumberCondition_Type", NumberCondition_Type_name, NumberCondition_Type_value)
	proto.RegisterEnum("infoblox.api.StringArrayCondition_Type", StringArrayCondition_Type_name, StringArrayCondition_Type_value)
	proto.RegisterEnum("infoblox.api.NumberArrayCondition_Type", NumberArrayCondition_Type_name, NumberArrayCondition_Type_value)
	proto.RegisterType((*SortCriteria)(nil), "infoblox.api.SortCriteria")
	proto.RegisterType((*Sorting)(nil), "infoblox.api.Sorting")
	proto.RegisterType((*FieldSelection)(nil), "infoblox.api.FieldSelection")
	proto.RegisterMapType((map[string]*Field)(nil), "infoblox.api.FieldSelection.FieldsEntry")
	proto.RegisterType((*Field)(nil), "infoblox.api.Field")
	proto.RegisterMapType((map[string]*Field)(nil), "infoblox.api.Field.SubsEntry")
	proto.RegisterType((*Filtering)(nil), "infoblox.api.Filtering")
	proto.RegisterType((*LogicalOperator)(nil), "infoblox.api.LogicalOperator")
	proto.RegisterType((*StringCondition)(nil), "infoblox.api.StringCondition")
	proto.RegisterType((*NumberCondition)(nil), "infoblox.api.NumberCondition")
	proto.RegisterType((*NullCondition)(nil), "infoblox.api.NullCondition")
	proto.RegisterType((*StringArrayCondition)(nil), "infoblox.api.StringArrayCondition")
	proto.RegisterType((*NumberArrayCondition)(nil), "infoblox.api.NumberArrayCondition")
	proto.RegisterType((*Pagination)(nil), "infoblox.api.Pagination")
	proto.RegisterType((*PageInfo)(nil), "infoblox.api.PageInfo")
	proto.RegisterType((*Searching)(nil), "infoblox.api.Searching")
}

func init() {
	proto.RegisterFile("github.com/infobloxopen/atlas-app-toolkit/query/collection_operators.proto", fileDescriptor_7b72dfd3c08d3120)
}

var fileDescriptor_7b72dfd3c08d3120 = []byte{
	// 1180 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0xd1, 0x72, 0xda, 0x46,
	0x17, 0x46, 0x20, 0x61, 0xeb, 0x60, 0xb0, 0xb2, 0xe6, 0x77, 0xb0, 0x9d, 0xfc, 0x71, 0x35, 0x9d,
	0xa9, 0x3b, 0x53, 0xc3, 0x94, 0x4e, 0xd3, 0x8c, 0x73, 0x53, 0x62, 0x93, 0xda, 0x19, 0xc7, 0x76,
	0x04, 0xbd, 0xc9, 0x0d, 0xb3, 0xe0, 0x45, 0xde, 0xb1, 0xac, 0x55, 0xa5, 0x25, 0x2d, 0x79, 0x80,
	0x3e, 0x80, 0x2f, 0x33, 0x7d, 0x8a, 0xde, 0xf6, 0x05, 0x7a, 0xd7, 0x87, 0xe8, 0x8b, 0x74, 0x76,
	0x25, 0x81, 0x10, 0x72, 0x0c, 0xc9, 0x0d, 0xd2, 0x9e, 0x39, 0xe7, 0x3b, 0xdf, 0x77, 0xf6, 0x13,
	0x5a, 0xc1, 0x2b, 0x9b, 0xf2, 0xab, 0x51, 0xbf, 0x3e, 0x60, 0x37, 0x0d, 0xea, 0x0e, 0x59, 0xdf,
	0x61, 0xbf, 0x31, 0x8f, 0xb8, 0x0d, 0xcc, 0x1d, 0x1c, 0xec, 0x63, 0xcf, 0xdb, 0xe7, 0x8c, 0x39,
	0xd7, 0x94, 0x37, 0x7e, 0x19, 0x11, 0x7f, 0xdc, 0x18, 0x30, 0xc7, 0x21, 0x03, 0x4e, 0x99, 0xdb,
	0x63, 0x1e, 0xf1, 0x31, 0x67, 0x7e, 0x50, 0xf7, 0x7c, 0xc6, 0x19, 0x5a, 0x8b, 0x01, 0xea, 0xd8,
	0xa3, 0xdb, 0xdf, 0xc8, 0xe0, 0x60, 0xdf, 0x26, 0xee, 0x7e, 0xf0, 0x2b, 0xb6, 0x6d, 0xe2, 0x37,
	0x98, 0x27, 0x0a, 0x83, 0x06, 0x76, 0x5d, 0xc6, 0xb1, 0xbc, 0x0f, 0x6b, 0x4d, 0x0e, 0x6b, 0x1d,
	0xe6, 0xf3, 0x43, 0x9f, 0x72, 0xe2, 0x53, 0x8c, 0x0c, 0x28, 0x70, 0x6c, 0xd7, 0x94, 0x5d, 0x65,
	0x4f, 0xb7, 0xc4, 0x2d, 0x7a, 0x0a, 0x1a, 0xf3, 0x2f, 0x89, 0x5f, 0xcb, 0xef, 0x2a, 0x7b, 0x95,
	0xe6, 0x6e, 0x3d, 0xd9, 0xad, 0x9e, 0x2c, 0xae, 0x9f, 0x8b, 0x3c, 0x2b, 0x4c, 0x37, 0xb7, 0x41,
	0x93, 0x6b, 0xb4, 0x02, 0x85, 0x56, 0xe7, 0xd0, 0xc8, 0xa1, 0x55, 0x50, 0x8f, 0xda, 0x9d, 0x43,
	0x43, 0x31, 0x31, 0xac, 0x88, 0x42, 0xea, 0xda, 0xe8, 0x19, 0xe8, 0x83, 0xa8, 0x3e, 0xa8, 0x29,
	0xbb, 0x85, 0xbd, 0x52, 0x73, 0xfb, 0xee, 0x16, 0xd6, 0x34, 0xf9, 0xe0, 0xd1, 0x6d, 0x6b, 0x0b,
	0x1e, 0x36, 0x1f, 0xc8, 0x89, 0xc9, 0xcc, 0x20, 0xc4, 0xfc, 0x90, 0x57, 0x56, 0xcc, 0xbf, 0x15,
	0xa8, 0xbc, 0xa4, 0xc4, 0xb9, 0xec, 0x90, 0x68, 0x6e, 0xe8, 0x47, 0x28, 0x0e, 0x45, 0x24, 0xee,
	0xb3, 0x37, 0xdb, 0x67, 0x36, 0x3b, 0x5c, 0x06, 0x6d, 0x97, 0xfb, 0x63, 0x2b, 0xaa, 0xdb, 0x3e,
	0x83, 0x52, 0x22, 0x2c, 0x86, 0x75, 0x4d, 0xc6, 0xf1, 0xb0, 0xae, 0xc9, 0x18, 0x7d, 0x0d, 0xda,
	0x3b, 0xec, 0x8c, 0x88, 0x1c, 0x56, 0xa9, 0xb9, 0x91, 0xd1, 0xc1, 0x0a, 0x33, 0x0e, 0xf2, 0xcf,
	0x94, 0x83, 0x2f, 0x6f, 0x5b, 0x5f, 0xc0, 0x93, 0xe6, 0xd6, 0x54, 0x82, 0x6c, 0xd4, 0x0b, 0x62,
	0x16, 0x52, 0xca, 0x1f, 0x0a, 0x68, 0xb2, 0x14, 0x21, 0x50, 0x5d, 0x7c, 0x43, 0xa2, 0x8e, 0xf2,
	0x1e, 0x7d, 0x0b, 0x6a, 0x30, 0xea, 0x07, 0xb5, 0xbc, 0xd4, 0xf4, 0x38, 0xa3, 0x63, 0xbd, 0x33,
	0xea, 0x47, 0x42, 0x64, 0xea, 0xf6, 0x29, 0xe8, 0x93, 0xd0, 0x67, 0x8b, 0x30, 0x7f, 0x57, 0x41,
	0x7f, 0x49, 0x1d, 0xb1, 0x2b, 0xae, 0x8d, 0x9e, 0xc3, 0x6a, 0xec, 0x4f, 0x89, 0x39, 0x47, 0xe9,
	0x94, 0xd9, 0x74, 0x80, 0x9d, 0xf3, 0x28, 0xe9, 0x38, 0x67, 0x4d, 0x0a, 0xd0, 0x2b, 0x30, 0x02,
	0x2e, 0x60, 0x7a, 0x03, 0xe6, 0x5e, 0x52, 0x31, 0x81, 0x88, 0x44, 0x0a, 0xa4, 0x23, 0xb3, 0x0e,
	0xe3, 0xa4, 0xe3, 0x9c, 0xb5, 0x1e, 0xcc, 0x86, 0x04, 0x96, 0x3b, 0xba, 0xe9, 0x13, 0x3f, 0x81,
	0x55, 0xc8, 0xc2, 0x3a, 0x93, 0x59, 0x33, 0x58, 0xee, 0x6c, 0x08, 0x1d, 0x41, 0xc5, 0x1d, 0x39,
	0x4e, 0x02, 0x49, 0x95, 0x48, 0x3b, 0x69, 0x24, 0xc7, 0x49, 0xe2, 0x94, 0xdd, 0x64, 0x00, 0xbd,
	0x85, 0xcd, 0x48, 0x1d, 0xf6, 0x7d, 0x3c, 0x4e, 0xa0, 0x69, 0x12, 0xcd, 0xcc, 0xd2, 0xd8, 0x12,
	0xa9, 0x49, 0xd0, 0x6a, 0x90, 0x11, 0x17, 0xd8, 0x91, 0xda, 0x34, 0x76, 0x31, 0x0b, 0x3b, 0xd4,
	0x3c, 0x8f, 0xed, 0x66, 0xc4, 0x0f, 0xfe, 0x7f, 0xdb, 0xda, 0x81, 0xad, 0xe6, 0x46, 0xd2, 0xa5,
	0xd1, 0x76, 0x0b, 0x7f, 0xbe, 0x28, 0x82, 0xea, 0x33, 0xc6, 0xcd, 0x3f, 0x75, 0x58, 0x4f, 0xed,
	0x2e, 0x3a, 0x82, 0xb2, 0x43, 0x86, 0xbc, 0xb7, 0xac, 0x27, 0xd6, 0x44, 0xd5, 0x04, 0xa5, 0x03,
	0xff, 0x93, 0x28, 0x9f, 0x6a, 0x8e, 0x0d, 0x51, 0x9d, 0x0a, 0x4f, 0x40, 0x3f, 0xd5, 0x25, 0x12,
	0x34, 0x15, 0x46, 0xaf, 0x61, 0x23, 0x02, 0x5d, 0xde, 0x2e, 0x0f, 0x42, 0xc0, 0xa4, 0x65, 0x06,
	0xb0, 0x93, 0x14, 0x9e, 0xde, 0xdb, 0xd2, 0x12, 0xbe, 0xa9, 0x4d, 0x67, 0x90, 0xf2, 0x4e, 0xdc,
	0xe4, 0x0e, 0x03, 0xad, 0x2d, 0x61, 0xa0, 0xda, 0x74, 0x26, 0xa9, 0x26, 0x2f, 0xa1, 0xe2, 0x53,
	0xfb, 0x2a, 0xe1, 0x04, 0x6d, 0x11, 0x27, 0x28, 0x56, 0x59, 0x96, 0x4d, 0xac, 0xf0, 0x33, 0x6c,
	0x86, 0x38, 0x73, 0x5e, 0x28, 0x2e, 0xe2, 0x05, 0xc5, 0xaa, 0xca, 0xf2, 0xb4, 0x19, 0x26, 0xb0,
	0x73, 0x6e, 0x58, 0x59, 0xc4, 0x0d, 0x31, 0x6c, 0xda, 0x0e, 0xe7, 0x50, 0x8d, 0x61, 0x67, 0xfc,
	0xb0, 0x7a, 0xbf, 0x1f, 0x14, 0x0b, 0x45, 0x90, 0x49, 0x43, 0x10, 0x78, 0x34, 0x23, 0x3f, 0xbd,
	0x59, 0xe5, 0x85, 0x1d, 0xa1, 0x58, 0x5b, 0x89, 0x49, 0xa4, 0x76, 0x6b, 0xd2, 0xe6, 0x0e, 0x4f,
	0x54, 0x16, 0xf6, 0x44, 0xdc, 0x26, 0xd3, 0x14, 0x4f, 0x41, 0xe5, 0x63, 0x8f, 0xd4, 0x74, 0x79,
	0xb4, 0x30, 0x3f, 0x6a, 0x85, 0x7a, 0x77, 0xec, 0x11, 0x4b, 0xe6, 0xa3, 0x27, 0x50, 0xa2, 0x41,
	0xcf, 0x25, 0x36, 0xe6, 0xf4, 0x1d, 0xa9, 0xc1, 0xae, 0xb2, 0xb7, 0x6a, 0x01, 0x0d, 0xce, 0xa2,
	0x88, 0xf9, 0x10, 0x54, 0x91, 0x2e, 0xcf, 0x1e, 0x67, 0x47, 0x46, 0x0e, 0x15, 0x21, 0x7f, 0x6e,
	0x19, 0x8a, 0xf8, 0xaf, 0x12, 0x16, 0x7d, 0xb1, 0x02, 0x9a, 0xa4, 0x65, 0xfe, 0xab, 0xc0, 0x7a,
	0xda, 0x0c, 0x8f, 0x01, 0xc2, 0xf7, 0xb0, 0x87, 0xf9, 0x95, 0x3c, 0x2c, 0xe8, 0x96, 0x2e, 0x23,
	0x17, 0x98, 0x5f, 0xa1, 0x6a, 0xf2, 0xfd, 0xa8, 0x47, 0xaf, 0xc2, 0x89, 0x96, 0x42, 0x96, 0x96,
	0x54, 0x87, 0x8f, 0x68, 0x51, 0xe7, 0xb4, 0xbc, 0x88, 0xb4, 0x14, 0x21, 0xdf, 0x7e, 0x63, 0xe4,
	0x90, 0x0e, 0xda, 0xeb, 0x56, 0xf7, 0xf0, 0xd8, 0x50, 0x44, 0xe8, 0xa7, 0xae, 0x91, 0x97, 0xd7,
	0xb6, 0x51, 0x10, 0xd7, 0xd3, 0xae, 0xa1, 0xca, 0x6b, 0xdb, 0xd0, 0x84, 0xfc, 0x93, 0xf6, 0x1b,
	0xa3, 0x68, 0xfe, 0xa3, 0xc0, 0x7a, 0xda, 0x9b, 0xcb, 0xa8, 0x54, 0x16, 0x52, 0x99, 0xea, 0xb0,
	0x94, 0xca, 0x7a, 0x4a, 0x65, 0x28, 0x4d, 0x89, 0xa4, 0xe5, 0x23, 0x69, 0x85, 0x48, 0x9a, 0x6a,
	0x9e, 0x43, 0x79, 0xf6, 0xc9, 0xb8, 0x47, 0x4e, 0x8a, 0x40, 0x7e, 0x8e, 0xc0, 0x5f, 0x0a, 0x54,
	0x33, 0x9f, 0x85, 0x7b, 0x80, 0x37, 0xa1, 0x28, 0x47, 0x13, 0x9e, 0xc0, 0x74, 0x2b, 0x5a, 0xa1,
	0xe7, 0x33, 0x93, 0xfa, 0xea, 0xfe, 0x27, 0x72, 0xa9, 0x71, 0x55, 0xa6, 0xe3, 0x3a, 0x39, 0x33,
	0x72, 0x92, 0x7d, 0xe6, 0x23, 0xb6, 0x14, 0x7b, 0x65, 0x31, 0xf6, 0x59, 0x8d, 0x3e, 0x8b, 0xfd,
	0x07, 0x05, 0xe0, 0x02, 0xdb, 0xd4, 0xc5, 0x31, 0x67, 0x0f, 0xdb, 0xa4, 0xc7, 0xd9, 0x35, 0x71,
	0xa3, 0x93, 0xa9, 0x2e, 0x22, 0x5d, 0x11, 0x10, 0x9c, 0xd9, 0x70, 0x18, 0x10, 0x2e, 0x77, 0x51,
	0xb3, 0xa2, 0x95, 0x70, 0xac, 0x43, 0x6f, 0x28, 0x97, 0xa4, 0x35, 0x2b, 0x5c, 0x20, 0x13, 0xca,
	0x34, 0xe8, 0x71, 0xc6, 0xb1, 0xd3, 0x0b, 0xe8, 0xfb, 0x98, 0x4e, 0x89, 0x06, 0x5d, 0x11, 0xeb,
	0xd0, 0xf7, 0xe4, 0x60, 0xe7, 0xb6, 0x55, 0x83, 0xcd, 0xa6, 0x31, 0x3d, 0xe1, 0x78, 0x82, 0x4d,
	0xf8, 0x25, 0xc1, 0x61, 0xf5, 0x02, 0xdb, 0xe4, 0xc4, 0x1d, 0xb2, 0xfb, 0x98, 0x21, 0x50, 0x65,
	0x8b, 0x90, 0x97, 0xbc, 0x4f, 0xb0, 0x2d, 0xcc, 0xb0, 0x7d, 0x0c, 0x90, 0x22, 0x55, 0xb0, 0x74,
	0x1e, 0x53, 0x32, 0x5b, 0xa0, 0x77, 0x08, 0xf6, 0x07, 0x57, 0xe2, 0x50, 0x5d, 0x05, 0x4d, 0x7e,
	0x05, 0x46, 0x1d, 0xc3, 0x45, 0xc6, 0xb9, 0x2c, 0x90, 0x15, 0xbd, 0xfe, 0x58, 0x9e, 0xcb, 0x7e,
	0x78, 0xfb, 0xfd, 0x92, 0x5f, 0x99, 0xcf, 0xe5, 0x6f, 0xbf, 0x28, 0xbf, 0x0d, 0xbf, 0xfb, 0x2f,
	0x00, 0x00, 0xff, 0xff, 0x8b, 0x24, 0x25, 0x2c, 0xa5, 0x0e, 0x00, 0x00,
}
