// Code generated by protoc-gen-go. DO NOT EDIT.
// source: resource.proto

package resource // import "github.com/infobloxopen/atlas-app-toolkit/rpc/resource"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// A number of application services require a mechanism to
// encode the identity of a particular resource across applications.
// The resource identifiers consist of the application ID,
// an application-defined resource type,
// and an application-defined ID for that resource
type Identifier struct {
	// An application identifier that will be used among
	// other infrastructure services to identify the application
	ApplicationName string `protobuf:"bytes,1,opt,name=application_name,json=applicationName" json:"application_name,omitempty"`
	// An application specific type name of a resource
	ResourceType string `protobuf:"bytes,2,opt,name=resource_type,json=resourceType" json:"resource_type,omitempty"`
	// An application specific resource identity of a resource
	ResourceId           string   `protobuf:"bytes,3,opt,name=resource_id,json=resourceId" json:"resource_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Identifier) Reset()         { *m = Identifier{} }
func (m *Identifier) String() string { return proto.CompactTextString(m) }
func (*Identifier) ProtoMessage()    {}
func (*Identifier) Descriptor() ([]byte, []int) {
	return fileDescriptor_resource_53c208b01ac1ebc4, []int{0}
}
func (m *Identifier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Identifier.Unmarshal(m, b)
}
func (m *Identifier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Identifier.Marshal(b, m, deterministic)
}
func (dst *Identifier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identifier.Merge(dst, src)
}
func (m *Identifier) XXX_Size() int {
	return xxx_messageInfo_Identifier.Size(m)
}
func (m *Identifier) XXX_DiscardUnknown() {
	xxx_messageInfo_Identifier.DiscardUnknown(m)
}

var xxx_messageInfo_Identifier proto.InternalMessageInfo

func (m *Identifier) GetApplicationName() string {
	if m != nil {
		return m.ApplicationName
	}
	return ""
}

func (m *Identifier) GetResourceType() string {
	if m != nil {
		return m.ResourceType
	}
	return ""
}

func (m *Identifier) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

func init() {
	proto.RegisterType((*Identifier)(nil), "atlas.rpc.Identifier")
}

func init() { proto.RegisterFile("resource.proto", fileDescriptor_resource_53c208b01ac1ebc4) }

var fileDescriptor_resource_53c208b01ac1ebc4 = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xbf, 0x4b, 0xc4, 0x40,
	0x10, 0x85, 0x89, 0x82, 0x90, 0xf5, 0x27, 0x5b, 0xa5, 0x53, 0xb4, 0xd1, 0x22, 0xd9, 0xc2, 0xd2,
	0x42, 0xb4, 0x4b, 0x63, 0x21, 0x56, 0x36, 0x61, 0xb3, 0x99, 0xdc, 0x0d, 0xb7, 0xd9, 0x19, 0x36,
	0x13, 0xb8, 0x14, 0xf7, 0xbf, 0x1f, 0x2c, 0xec, 0x71, 0xdd, 0xf0, 0xf1, 0xcd, 0xe3, 0x3d, 0x75,
	0x17, 0x61, 0xa6, 0x25, 0x3a, 0x68, 0x38, 0x92, 0x90, 0x2e, 0xad, 0x78, 0x3b, 0x37, 0x91, 0xdd,
	0xf3, 0x41, 0xa9, 0x76, 0x80, 0x20, 0x38, 0x22, 0x44, 0xfd, 0xa6, 0x1e, 0x2c, 0xb3, 0x47, 0x67,
	0x05, 0x29, 0x74, 0xc1, 0x4e, 0x50, 0x15, 0x4f, 0xc5, 0x6b, 0xf9, 0x7b, 0x7f, 0xc6, 0x7f, 0xec,
	0x04, 0xfa, 0x45, 0xdd, 0xe6, 0xd4, 0x4e, 0x56, 0x86, 0xea, 0x22, 0x79, 0x37, 0x19, 0xfe, 0xad,
	0x0c, 0xfa, 0x51, 0x5d, 0x9f, 0x24, 0x1c, 0xaa, 0xcb, 0xa4, 0xa8, 0x8c, 0xda, 0xe1, 0xfb, 0xeb,
	0xff, 0x73, 0x83, 0xb2, 0x5d, 0xfa, 0xc6, 0xd1, 0x64, 0x30, 0x8c, 0xd4, 0x7b, 0xda, 0x13, 0x43,
	0x30, 0xa9, 0x63, 0x6d, 0x99, 0x6b, 0x21, 0xf2, 0x3b, 0x14, 0x13, 0xd9, 0x99, 0xfc, 0xfb, 0x91,
	0x8f, 0xfe, 0x2a, 0x6d, 0x7a, 0x3f, 0x06, 0x00, 0x00, 0xff, 0xff, 0x55, 0xdb, 0x1b, 0x34, 0xe5,
	0x00, 0x00, 0x00,
}
