// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/errfields/error_fields.proto

package errfields // import "github.com/infobloxopen/atlas-app-toolkit/rpc/errfields"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// FieldsInfo is a default representation of field details that conforms
// REST API Syntax Specification
type FieldInfo struct {
	Fields               map[string]*StringListValue `protobuf:"bytes,1,rep,name=fields" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *FieldInfo) Reset()         { *m = FieldInfo{} }
func (m *FieldInfo) String() string { return proto.CompactTextString(m) }
func (*FieldInfo) ProtoMessage()    {}
func (*FieldInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_error_fields_c23cb26b1f055392, []int{0}
}
func (m *FieldInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldInfo.Unmarshal(m, b)
}
func (m *FieldInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldInfo.Marshal(b, m, deterministic)
}
func (dst *FieldInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldInfo.Merge(dst, src)
}
func (m *FieldInfo) XXX_Size() int {
	return xxx_messageInfo_FieldInfo.Size(m)
}
func (m *FieldInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FieldInfo proto.InternalMessageInfo

func (m *FieldInfo) GetFields() map[string]*StringListValue {
	if m != nil {
		return m.Fields
	}
	return nil
}

type StringListValue struct {
	Values               []string `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringListValue) Reset()         { *m = StringListValue{} }
func (m *StringListValue) String() string { return proto.CompactTextString(m) }
func (*StringListValue) ProtoMessage()    {}
func (*StringListValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_error_fields_c23cb26b1f055392, []int{1}
}
func (m *StringListValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringListValue.Unmarshal(m, b)
}
func (m *StringListValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringListValue.Marshal(b, m, deterministic)
}
func (dst *StringListValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringListValue.Merge(dst, src)
}
func (m *StringListValue) XXX_Size() int {
	return xxx_messageInfo_StringListValue.Size(m)
}
func (m *StringListValue) XXX_DiscardUnknown() {
	xxx_messageInfo_StringListValue.DiscardUnknown(m)
}

var xxx_messageInfo_StringListValue proto.InternalMessageInfo

func (m *StringListValue) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*FieldInfo)(nil), "atlas.rpc.FieldInfo")
	proto.RegisterMapType((map[string]*StringListValue)(nil), "atlas.rpc.FieldInfo.FieldsEntry")
	proto.RegisterType((*StringListValue)(nil), "atlas.rpc.StringListValue")
}

func init() {
	proto.RegisterFile("rpc/errfields/error_fields.proto", fileDescriptor_error_fields_c23cb26b1f055392)
}

var fileDescriptor_error_fields_c23cb26b1f055392 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x28, 0x2a, 0x48, 0xd6,
	0x4f, 0x2d, 0x2a, 0x4a, 0xcb, 0x4c, 0xcd, 0x49, 0x29, 0x06, 0xb1, 0xf2, 0x8b, 0xe2, 0x21, 0x1c,
	0xbd, 0x82, 0xa2, 0xfc, 0x92, 0x7c, 0x21, 0xce, 0xc4, 0x92, 0x9c, 0xc4, 0x62, 0xbd, 0xa2, 0x82,
	0x64, 0xa5, 0x39, 0x8c, 0x5c, 0x9c, 0x6e, 0x20, 0x39, 0xcf, 0xbc, 0xb4, 0x7c, 0x21, 0x0b, 0x2e,
	0x36, 0x88, 0x42, 0x09, 0x46, 0x05, 0x66, 0x0d, 0x6e, 0x23, 0x05, 0x3d, 0xb8, 0x4a, 0x3d, 0xb8,
	0x2a, 0x08, 0xab, 0xd8, 0x35, 0xaf, 0xa4, 0xa8, 0x32, 0x08, 0xaa, 0x5e, 0x2a, 0x94, 0x8b, 0x1b,
	0x49, 0x58, 0x48, 0x80, 0x8b, 0x39, 0x3b, 0xb5, 0x52, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08,
	0xc4, 0x14, 0x32, 0xe0, 0x62, 0x2d, 0x4b, 0xcc, 0x29, 0x4d, 0x95, 0x60, 0x52, 0x60, 0xd4, 0xe0,
	0x36, 0x92, 0x42, 0x32, 0x39, 0xb8, 0xa4, 0x28, 0x33, 0x2f, 0xdd, 0x27, 0xb3, 0xb8, 0x24, 0x0c,
	0xa4, 0x22, 0x08, 0xa2, 0xd0, 0x8a, 0xc9, 0x82, 0x51, 0x49, 0x93, 0x8b, 0x1f, 0x4d, 0x56, 0x48,
	0x8c, 0x8b, 0x0d, 0x2c, 0x0f, 0x71, 0x23, 0x67, 0x10, 0x94, 0xe7, 0xe4, 0x1c, 0xe5, 0x98, 0x9e,
	0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f, 0xab, 0x9f, 0x99, 0x97, 0x96, 0x9f, 0x94, 0x93,
	0x5f, 0x91, 0x5f, 0x90, 0x9a, 0xa7, 0x0f, 0xb6, 0x4a, 0x37, 0xb1, 0xa0, 0x40, 0xb7, 0x24, 0x3f,
	0x3f, 0x27, 0x3b, 0xb3, 0x44, 0x1f, 0x25, 0x88, 0xac, 0xe1, 0xac, 0x24, 0x36, 0x70, 0x00, 0x19,
	0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x8b, 0x05, 0xf7, 0xbe, 0x44, 0x01, 0x00, 0x00,
}
